[tool.poetry]
name = "private-project-template"
version = "0.1.0"
description = "A template design for private project"
authors = [
    "Tzu-Hsiang Wang <phoenixteally@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"
numpy = ">=2.0.0,<3.0.0"
scikit-learn = "^1.8.0"
pytest = "^9.0.2"
flake8 = "^7.3.0"
pytest-cov = "^7.0.0"
opencv-python = "^4.12.0.88"
scikit-image = "^0.26.0"
isort = "^7.0.0"
poethepoet = "^0.39.0"
albumentations = "^2.0.8"
optree = "^0.18.0"
lightning = "^2.6.1"
matplotlab = "^0.1.14"

[tool.poe.tasks]
install = [
    "install-torch"
    ]

install-torch = "pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"